import constructDeconstruct from './index';

test('constructDeconstruct', () => {
  expect(constructDeconstruct('')).toEqual([]);
  expect(constructDeconstruct('Hello')).toEqual([
    'H',
    'He',
    'Hel',
    'Hell',
    'Hello',
    'Hell',
    'Hel',
    'He',
    'H',
  ]);
  expect(constructDeconstruct('edabit')).toEqual([
    'e',
    'ed',
    'eda',
    'edab',
    'edabi',
    'edabit',
    'edabi',
    'edab',
    'eda',
    'ed',
    'e',
  ]);
  expect(constructDeconstruct('the sun')).toEqual([
    't',
    'th',
    'the',
    'the ',
    'the s',
    'the su',
    'the sun',
    'the su',
    'the s',
    'the ',
    'the',
    'th',
    't',
  ]);
  expect(constructDeconstruct('        ')).toEqual([
    ' ',
    '  ',
    '   ',
    '    ',
    '     ',
    '      ',
    '       ',
    '        ',
    '       ',
    '      ',
    '     ',
    '    ',
    '   ',
    '  ',
    ' ',
  ]);
  expect(constructDeconstruct('123456789')).toEqual([
    '1',
    '12',
    '123',
    '1234',
    '12345',
    '123456',
    '1234567',
    '12345678',
    '123456789',
    '12345678',
    '1234567',
    '123456',
    '12345',
    '1234',
    '123',
    '12',
    '1',
  ]);
  expect(constructDeconstruct('s p a c e s')).toEqual([
    's',
    's ',
    's p',
    's p ',
    's p a',
    's p a ',
    's p a c',
    's p a c ',
    's p a c e',
    's p a c e ',
    's p a c e s',
    's p a c e ',
    's p a c e',
    's p a c ',
    's p a c',
    's p a ',
    's p a',
    's p ',
    's p',
    's ',
    's',
  ]);
  expect(constructDeconstruct('so long partner')).toEqual([
    's',
    'so',
    'so ',
    'so l',
    'so lo',
    'so lon',
    'so long',
    'so long ',
    'so long p',
    'so long pa',
    'so long par',
    'so long part',
    'so long partn',
    'so long partne',
    'so long partner',
    'so long partne',
    'so long partn',
    'so long part',
    'so long par',
    'so long pa',
    'so long p',
    'so long ',
    'so long',
    'so lon',
    'so lo',
    'so l',
    'so ',
    'so',
    's',
  ]);
  expect(constructDeconstruct('edabit is a awesome')).toEqual([
    'e',
    'ed',
    'eda',
    'edab',
    'edabi',
    'edabit',
    'edabit ',
    'edabit i',
    'edabit is',
    'edabit is ',
    'edabit is a',
    'edabit is a ',
    'edabit is a a',
    'edabit is a aw',
    'edabit is a awe',
    'edabit is a awes',
    'edabit is a aweso',
    'edabit is a awesom',
    'edabit is a awesome',
    'edabit is a awesom',
    'edabit is a aweso',
    'edabit is a awes',
    'edabit is a awe',
    'edabit is a aw',
    'edabit is a a',
    'edabit is a ',
    'edabit is a',
    'edabit is ',
    'edabit is',
    'edabit i',
    'edabit ',
    'edabit',
    'edabi',
    'edab',
    'eda',
    'ed',
    'e',
  ]);
});
